kotlin.code.style=official
exposedVersion=0.61.0

mavenCentralUserName=w649BG54
mavenCentralPassword=+dKpgAdB/5+8QRYO2e24yHVBPtIeLxjJEMq+wEFcUaAq

signing.keyId=0FEEA70A
signing.password=
#signing.inMemoryKey=-----BEGIN PGP PRIVATE KEY BLOCK----- lFgEZ96nRBYJKwYBBAHaRw8BAQdAAzJTmZVq3kC1amPW9CbzA508LM525HNONxfBbByjk9AAAQDa7UAmsZuIaJZ8LekJQbLhf0IgctNt8/XoMl8cyDaFJxAptB/snbTtg5zsiJggPGFwbzIwNzNAb3V0bG9vay5jb20+iJkEExYKAEEWIQTz7NwjOqF0ApsARNjClHipD+6nCgUCZ96nRAIbAwUJBaRsbAULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRDClHipD+6nCrghAQCm1E3b45Zp6D/YiDA4HTOl2IPsDE3m3x0MQR8Odr2YhgD/RGQww7/RSBzr+Re6Ma7SfVARb1USl9eZF/Ae6wMIvwmcXQRn3qdEEgorBgEEAZdVAQUBAQdAV9Ue6qk+a9OIObDMZortscZmwcNKCCM37L9GavMq7lUDAQgHAAD/UdqB+HPtA+Qs7myRrdAhlGUROcZcl4L0C0w4ApWbpVAQx4h+BBgWCgAmFiEE8+zcIzqhdAKbAETYwpR4qQ/upwoFAmfep0QCGwwFCQWkbGwACgkQwpR4qQ/upwr+ewD+NjXF4nbzZKLAOh6UBhtp4/inJlHe0PPf8IYn8zhj+q0BALv13HU4zQtaaDU0ZjbggGPetnMkjCAL5kESx/BwaxEO =Rw+8 -----END PGP PRIVATE KEY BLOCK-----
signing.secretKeyRingFile= C:\\Users\\PC\\Desktop\\GrassLib\\gpg\\key.asc
# C:\Users\PC\Desktop\GrassLib\gpg