name: GrassLib
main: com.github.grassproject.grassLib.GrassLib
version: ${version}
api-version: 1.21
authors: [ GrassProject ]
softdepend: [
  ItemsAdder,
  MMOItems,
  Oraxen,
  Nexo,
  ProtoclLib
]
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.10